"""ajout_statut_inscription

Revision ID: 27eb788df392
Revises: 298435731f6d
Create Date: 2026-06-17 02:32:44.501097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27eb788df392'
down_revision: Union[str, Sequence[str], None] = '298435731f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eleves', sa.Column('statut_inscription', sa.String(), nullable=True))
    op.alter_column('eleves', 'matricule',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('eleves', 'nom',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('eleves', 'prenom',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('eleves', 'sexe',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('eleves', 'date_naissance',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_eleves_nom'), 'eleves', ['nom'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eleves_nom'), table_name='eleves')
    op.alter_column('eleves', 'date_naissance',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('eleves', 'sexe',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('eleves', 'prenom',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('eleves', 'nom',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('eleves', 'matricule',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('eleves', 'statut_inscription')
    # ### end Alembic commands ###
