"""Mise a jour de la table Classes

Revision ID: 298435731f6d
Revises: 359665ea5550
Create Date: 2026-06-16 10:40:25.283489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298435731f6d'
down_revision: Union[str, Sequence[str], None] = '359665ea5550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('salle', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('professeur_principal_id', sa.Integer(), nullable=True))
    op.alter_column('classes', 'nom',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('classes', 'niveau',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_classes_nom'), table_name='classes')
    op.create_index(op.f('ix_classes_nom'), 'classes', ['nom'], unique=False)
    op.create_foreign_key(None, 'classes', 'employes', ['professeur_principal_id'], ['id'])
    op.drop_column('classes', 'annee_scolaire')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('annee_scolaire', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_index(op.f('ix_classes_nom'), table_name='classes')
    op.create_index(op.f('ix_classes_nom'), 'classes', ['nom'], unique=True)
    op.alter_column('classes', 'niveau',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('classes', 'nom',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('classes', 'professeur_principal_id')
    op.drop_column('classes', 'salle')
    # ### end Alembic commands ###
