"""Ajout des infos complementaires eleves

Revision ID: 2e1476f7535d
Revises: 6fdd555fe790
Create Date: 2026-06-18 10:09:58.496958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1476f7535d'
down_revision: Union[str, Sequence[str], None] = '6fdd555fe790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eleves', sa.Column('lieu_naissance', sa.String(), nullable=True))
    op.add_column('eleves', sa.Column('adresse', sa.String(), nullable=True))
    op.add_column('eleves', sa.Column('telephone_parents', sa.String(), nullable=True))
    op.add_column('eleves', sa.Column('responsable_legal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eleves', 'responsable_legal')
    op.drop_column('eleves', 'telephone_parents')
    op.drop_column('eleves', 'adresse')
    op.drop_column('eleves', 'lieu_naissance')
    # ### end Alembic commands ###
