"""ajout_mot_de_passe

Revision ID: 415f3cc1a3ca
Revises: bccbd99438ba
Create Date: 2026-06-15 15:58:06.105597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415f3cc1a3ca'
down_revision: Union[str, Sequence[str], None] = 'bccbd99438ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('mot_de_passe', sa.String(), nullable=True))
    op.add_column('utilisateurs', sa.Column('est_actif', sa.Boolean(), nullable=True))
    op.alter_column('utilisateurs', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('utilisateurs', 'nom',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('utilisateurs', 'prenom',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('utilisateurs', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('utilisateurs', 'actif')
    op.drop_column('utilisateurs', 'mot_de_passe_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('mot_de_passe_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('utilisateurs', sa.Column('actif', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('utilisateurs', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('utilisateurs', 'prenom',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('utilisateurs', 'nom',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('utilisateurs', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('utilisateurs', 'est_actif')
    op.drop_column('utilisateurs', 'mot_de_passe')
    # ### end Alembic commands ###
