"""Ajout observations a la table Eleve

Revision ID: 6fdd555fe790
Revises: 27eb788df392
Create Date: 2026-06-18 09:54:05.991282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdd555fe790'
down_revision: Union[str, Sequence[str], None] = '27eb788df392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eleves', sa.Column('observations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eleves', 'observations')
    # ### end Alembic commands ###
