"""Alignement Backend et Frontend

Revision ID: a909a260dc14
Revises: 2e1476f7535d
Create Date: 2026-06-19 03:29:38.426272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a909a260dc14'
down_revision: Union[str, Sequence[str], None] = '2e1476f7535d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('prof_principal', sa.String(), nullable=True))
    op.drop_constraint(op.f('classes_professeur_principal_id_fkey'), 'classes', type_='foreignkey')
    op.drop_column('classes', 'professeur_principal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('professeur_principal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('classes_professeur_principal_id_fkey'), 'classes', 'employes', ['professeur_principal_id'], ['id'])
    op.drop_column('classes', 'prof_principal')
    # ### end Alembic commands ###
