"""Initialisation propre

Revision ID: baa8b28d7f3b
Revises: 
Create Date: 2026-06-21 02:27:25.949155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa8b28d7f3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('niveau', sa.String(), nullable=True),
    sa.Column('salle', sa.String(), nullable=True),
    sa.Column('prof_principal', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index(op.f('ix_classes_nom'), 'classes', ['nom'], unique=False)
    op.create_table('etablissement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('directeur', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('annee_scolaire', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etablissement_id'), 'etablissement', ['id'], unique=False)
    op.create_table('matieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('couleur', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matieres_id'), 'matieres', ['id'], unique=False)
    op.create_index(op.f('ix_matieres_nom'), 'matieres', ['nom'], unique=True)
    op.create_table('salles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('capacite', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salles_id'), 'salles', ['id'], unique=False)
    op.create_index(op.f('ix_salles_nom'), 'salles', ['nom'], unique=True)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('mot_de_passe', sa.String(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_table('eleves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('sexe', sa.String(), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('lieu_naissance', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('telephone_parents', sa.String(), nullable=True),
    sa.Column('responsable_legal', sa.String(), nullable=True),
    sa.Column('scolarite_totale', sa.Float(), nullable=True),
    sa.Column('statut_inscription', sa.String(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eleves_id'), 'eleves', ['id'], unique=False)
    op.create_index(op.f('ix_eleves_matricule'), 'eleves', ['matricule'], unique=True)
    op.create_index(op.f('ix_eleves_nom'), 'eleves', ['nom'], unique=False)
    op.create_table('employes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('sexe', sa.String(), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('fonction', sa.String(), nullable=True),
    sa.Column('date_recrutement', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_index(op.f('ix_employes_email'), 'employes', ['email'], unique=True)
    op.create_index(op.f('ix_employes_id'), 'employes', ['id'], unique=False)
    op.create_index(op.f('ix_employes_nom'), 'employes', ['nom'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=False),
    sa.Column('motif', sa.String(), nullable=False),
    sa.Column('mode_paiement', sa.String(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paiements_id'), 'paiements', ['id'], unique=False)
    op.create_table('seances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_seance', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.Column('prof_id', sa.Integer(), nullable=True),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('salle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prof_id'], ['employes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salle_id'], ['salles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seances_id'), 'seances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seances_id'), table_name='seances')
    op.drop_table('seances')
    op.drop_index(op.f('ix_paiements_id'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_employes_nom'), table_name='employes')
    op.drop_index(op.f('ix_employes_id'), table_name='employes')
    op.drop_index(op.f('ix_employes_email'), table_name='employes')
    op.drop_table('employes')
    op.drop_index(op.f('ix_eleves_nom'), table_name='eleves')
    op.drop_index(op.f('ix_eleves_matricule'), table_name='eleves')
    op.drop_index(op.f('ix_eleves_id'), table_name='eleves')
    op.drop_table('eleves')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_salles_nom'), table_name='salles')
    op.drop_index(op.f('ix_salles_id'), table_name='salles')
    op.drop_table('salles')
    op.drop_index(op.f('ix_matieres_nom'), table_name='matieres')
    op.drop_index(op.f('ix_matieres_id'), table_name='matieres')
    op.drop_table('matieres')
    op.drop_index(op.f('ix_etablissement_id'), table_name='etablissement')
    op.drop_table('etablissement')
    op.drop_index(op.f('ix_classes_nom'), table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
